import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
import base64
import asyncio
from datetime import datetime

DEFAULT_EMAIL = os.getenv("DEFAULT_ALERT_EMAIL", "shibasish205@gmail.com")

async def send_report_email(
    recipient: str,
    selected_sections: list,
    report_data: dict,
    ai_summary: str,
    pdf_bytes: bytes = None
) -> dict:
    loop = asyncio.get_event_loop()
    
    # Validate email
    valid = _is_valid_email(recipient)
    send_to = recipient if valid else DEFAULT_EMAIL
    fallback_used = not valid

    result = await loop.run_in_executor(
        None, _send_sync, 
        send_to, selected_sections, report_data, ai_summary, pdf_bytes
    )
    result['fallbackUsed'] = fallback_used
    result['sentTo'] = send_to
    return result

def _is_valid_email(email: str) -> bool:
    import re
    if not email:
        return False
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return bool(re.match(pattern, email))

def _send_sync(to_email, sections, data, summary, pdf_bytes):
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"Ghana Cloud Intelligence Report — {datetime.now().strftime('%b %d, %Y')}"
        msg['From'] = os.getenv("MAIL_USERNAME", "shibasish205@gmail.com")
        msg['To'] = to_email

        html = f"""
<div style="background:#0a0000;color:#f2e6e6;
            font-family:monospace;padding:32px;
            max-width:600px;margin:0 auto;
            border:1px solid #993333;border-radius:8px">
  <h1 style="color:#993333;font-size:32px;margin:0">GHANA</h1>
  <p style="color:#c58a8a;margin:4px 0 24px">
    Cloud Cost Intelligence Report</p>
  <p style="color:#800000;font-size:12px">
    Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
  <hr style="border:none;border-top:1px solid #460000;margin:24px 0">

  <h2 style="color:#f2e6e6;font-size:18px">Overview Summary</h2>
  <table style="width:100%;border-collapse:collapse;margin-bottom:24px">
    <tr>
      <td style="padding:10px;border:1px solid #460000;color:#c58a8a">
        Total Cost</td>
      <td style="padding:10px;border:1px solid #460000;color:#993333;
                 font-weight:bold">${data.get('totalCost', 11750):,}</td>
    </tr>
    <tr style="background:#140000">
      <td style="padding:10px;border:1px solid #460000;color:#c58a8a">
        Money Saved</td>
      <td style="padding:10px;border:1px solid #460000;color:#4ade80;
                 font-weight:bold">${data.get('moneySaved', 5210):,}</td>
    </tr>
    <tr>
      <td style="padding:10px;border:1px solid #460000;color:#c58a8a">
        Active Anomalies</td>
      <td style="padding:10px;border:1px solid #460000;
                 color:#f2e6e6">{data.get('anomalies', 7)}</td>
    </tr>
    <tr style="background:#140000">
      <td style="padding:10px;border:1px solid #460000;color:#c58a8a">
        Optimizations Done</td>
      <td style="padding:10px;border:1px solid #460000;
                 color:#f2e6e6">{data.get('optimizations', 28)}</td>
    </tr>
  </table>

  <h2 style="color:#f2e6e6;font-size:18px">AI Executive Summary</h2>
  <p style="color:#d8b0b0;line-height:1.8;
            background:#140000;padding:16px;
            border-left:3px solid #993333;
            border-radius:4px">{summary}</p>

  <h2 style="color:#f2e6e6;font-size:18px">Report Sections</h2>
  <ul style="color:#d8b0b0">
    {''.join(f'<li style="margin:4px 0">{s}</li>' for s in sections)}
  </ul>

  <hr style="border:none;border-top:1px solid #460000;margin:24px 0">
  <p style="color:#460000;font-size:11px;text-align:center">
    Confidential — Generated by Ghana Cloud Intelligence Platform<br>
    Powered by Ghana AI
  </p>
</div>"""

        msg.attach(MIMEText(html, 'html'))

        if pdf_bytes:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(pdf_bytes)
            encoders.encode_base64(part)
            fname = f"ghana-report-{datetime.now().strftime('%Y%m%d')}.pdf"
            part.add_header(
                'Content-Disposition', f'attachment; filename="{fname}"'
            )
            msg.attach(part)

        try:
            with smtplib.SMTP(os.getenv("MAIL_SERVER", "smtp.gmail.com"), 
                              int(os.getenv("MAIL_PORT", 587))) as server:
                server.starttls()
                server.login(
                    os.getenv("MAIL_USERNAME"), 
                    os.getenv("MAIL_PASSWORD")
                )
                server.sendmail(
                    os.getenv("MAIL_USERNAME"), to_email, msg.as_string()
                )
            return {"success": True}
        except Exception as smtp_e:
            print("SMTP Error details:", smtp_e)
            return {"success": False, "error": str(smtp_e)}
            
    except Exception as e:
        return {"success": False, "error": str(e)}
